### ISSUE TITLE
Integrate with gyft2

### ISSUE THREAD

**Issue by athityakumar** [metakgp/erp-auto-login#21]
This browser extension can be used to automate the manual steps used in https://github.com/xypnox/gyft2 - upon clicking a button after logging into erp, the extension can automatically open the timetable page, POST the html to gyft2, fetch back the ics and download it on the browser's end.

Ping @xypnox @Ayushk4 @thealphadollar @DefCon-007

**Comment by thealphadollar** [comment]
Agreed, this can be done easily.

A simple flask api can do it with ease.

@xypnox.

**Comment by xypnox** [comment]
Can we somehow integrate this with the OG flask web app? so that the users
can either login or upload a html file of the timetable? This would be more
user friendly and reduce too many options.

**Comment by thealphadollar** [comment]
I'm more on the side of using the extension; it's more comfortable.

**Comment by xypnox** [comment]
Extension it is. I would suggest making it cross browser compatible (chrome
and firefox at least).

**Comment by thealphadollar** [comment]
This, I believe, is not needed anymore and the strong coupling introduced will lead to the slow and hindered future development of both projects.

**Comment by xypnox** [comment]
We just need to separate the functions that process the data to create calendar and have to input methods. Can you explain in detail how this increases the difficulty in maintaining the project? Bugs related to one form of input would probably be specific to that. There isn't much back and forth between the two methods. 

One of them fetches html from ERP, the other takes in from a file. I don't think adding just a few more lines of code (I hope) to add functionality to process the schedule html file will introduce enough bugs/difficulty in maintanence than the benefit of NOT SHARING ERP PASSWORD!

**Comment by athityakumar** [comment]
Yup, I agree w/ @xypnox. Ideally, the popup could just have a "Download timetable" button and you can have all the gyft-specific integrations working on that onClick() event handler. Shouldn't be much of a maintenance issue as the concerns will be pretty much separated.

Ofcourse, I'll leave you guys to decide whether it makes sense to built it rn or how to implement. 😄

**Comment by thealphadollar** [comment]
@athityakumar @xypnox I'm really sorry, I did not understand the issue well. I have a better idea now, thanks for helping me understand.

On a side note, we have a web version of the GYFT running (https://gyft.metakgp.org/) which we are actively maintaining every semester with updates. I would like to understand what benefit will this feature provide over the web version? One is that there will be no sharing of credentials to the server side, and that is, I personally believe, not a concern of students since we have the entire code made available openly for anyone to view and check, and same code is auto-deployed to heroku.

However, if you believe that adding this feature is worth the efforts, I'm all in. I would humbly request to add concrete steps on to how this should be approached in the description as many new contributors would be coming for Hacktoberfest and let's get this done! :sparkles: :package:

**Comment by proffapt** [comment]
With [ERP Login Extension](https://github.com/proffapt/iitkgp-erp-login-pypi) the login workflow is optimised for many scenarios (including testing and continuous login like in case of MFTP) and yes obviously OTP support, login workflow is not an issue anymore and it has been successfully incorporated into gyft itself now.
Gyft now doesn't require maintaining a separate subjects.json file.
Also, because of the extension it just takes removing one argument to toggle manual/automatic credentials filling.
And this is just one time job per semester, so it's fine even if we enter the credentials manually.

Hence, closing this issue.
