### ISSUE TITLE
Make an equivalent solution for smart phones

### ISSUE THREAD

**Issue by athityakumar** [metakgp/erp-auto-login#5]

**Comment by sahil-shubham** [comment]
What are the different solutions to this problem? I can just think of an app for now.

**Comment by thealphadollar** [comment]
Hey, @sahil-shubham Do you think this issue is worth the hassle?

Creating a mobile application specifically for this purpose is, in my opinion, not an efficient task to do. What I would prefer that we ask people who want to use the extension on phone to install [Kiwi Browser](https://9to5google.com/2019/04/16/hands-on-kiwi-browser-brings-full-chrome-extensions-to-android-gallery/) or [Yandex browser](https://yandex.com/support/browser-mobile-android-phone/personal-settings/extensions.html). So, if you want, please raise a PR with adding instructions that people can install these browsers if they wish to use the extension on mobile :sparkles: 

If a person is willing to install an application to automate the process in chrome, they will be equally willing to install a new browser on their phone and access ERP through there.

PS. This is just my viewpoint, if you wish to go ahead with developing an application, I'm all in for helping you out <3

**Comment by sahil-shubham** [comment]
@thealphadollar Thank you for taking the time to answer. I thought the same, one wouldn't be willing to install an app just for erp auto login, it's a very specific problem as google already takes care of other websites. 

I like your idea of adding instructions in README regarding the yandex or kiwi browser. I am going to make the necessary changes and raise a pull request soon.
